Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: "http://localhost:3000"
  copyright: Eric Rochester 2013
  analytics: UA-33512822-2

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://shielded-everglades-5738.herokuapp.com"
  <<: *defaults
